# Generated by Django 3.2.19 on 2023-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WastageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=50)),
                ('wastagename', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images')),
                ('cost', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('assignedto', models.CharField(max_length=50)),
                ('collectiondate', models.CharField(max_length=50)),
                ('adminstatus', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
